name: kafka-samples

services:
  zookeeper:
    image: zookeeper:3.7.2
    container_name: kafka-samples-zookeeper
    hostname: kafka-samples-zookeeper
    ports:
      - '2181:2181'
    volumes:
      - kafka-samples-zookeeper-data:/data
      - kafka-samples-zookeeper-datalog:/datalog
      - kafka-samples-zookeeper-logs:/logs

  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    container_name: kafka-samples-kafka
    hostname: kafka-samples-kafka
    ports:
      - '9092:9092'
    volumes:
      - kafka-samples-kafka:/kafka
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "kafka-samples:1:1"

volumes:
  kafka-samples-zookeeper-data:
  kafka-samples-zookeeper-datalog:
  kafka-samples-zookeeper-logs:
  kafka-samples-kafka: